N <-
c("S&P 500 Index", "Agilent Technologies Inc", "American Airlines Group Inc", 
"Advance Auto Parts Inc", "Apple Inc", "Abbvie Inc", "Amerisourcebergen Corp", 
"ABIOMED Inc", "Abbott Laboratories", "Accenture PLC", "Adobe Inc", 
"Analog Devices Inc", "Archer-Daniels-Midland Co", "Automatic Data Processing Inc", 
"Autodesk Inc", "Ameren Corp", "American Electric Power Company Inc", 
"AES Corp", "Aflac Inc", "American International Group Inc", 
"Apartment Investment and Management Co", "Assurant Inc", "Arthur J Gallagher & Co", 
"Akamai Technologies Inc", "Albemarle Corp", "Align Technology Inc", 
"Alaska Air Group Inc", "Allstate Corp", "Allegion PLC", "Alexion Pharmaceuticals Inc", 
"Applied Materials Inc", "Amcor PLC", "Advanced Micro Devices Inc", 
"AMETEK Inc", "Amgen Inc", "Ameriprise Financial Inc", "American Tower Corp", 
"Amazon.com Inc", "Arista Networks Inc", "ANSYS Inc", "Anthem Inc", 
"Aon PLC", "A. O. Smith Corp", "Apache Corp", "Air Products and Chemicals Inc", 
"Amphenol Corp", "Aptiv PLC", "Alexandria Real Estate Equities Inc", 
"Atmos Energy Corp", "Activision Blizzard Inc", "Avalonbay Communities Inc", 
"Broadcom Inc", "Avery Dennison Corp", "American Water Works Company Inc", 
"American Express Co", "Autozone Inc", "Boeing Co", "Bank of America Corp", 
"Baxter International Inc", "Best Buy Co Inc", "Becton Dickinson and Co", 
"Franklin Resources Inc", "Brown-Forman Corp", "Biogen Inc", 
"Bio Rad Laboratories Inc", "Bank of New York Mellon Corp", "Booking Holdings Inc", 
"Baker Hughes Co", "BlackRock Inc", "Ball Corp", "Bristol-Myers Squibb Co", 
"Broadridge Financial Solutions Inc", "Berkshire Hathaway Inc", 
"Boston Scientific Corp", "Borgwarner Inc", "Boston Properties Inc", 
"Citigroup Inc", "Conagra Brands Inc", "Cardinal Health Inc", 
"Carrier Global Corp", "Caterpillar Inc", "Chubb Ltd", "Cboe Global Markets Inc", 
"CBRE Group Inc", "Crown Castle International Corp", "Carnival Corp", 
"Cadence Design Systems Inc", "CDW Corp", "Celanese Corp", "Cerner Corp", 
"CF Industries Holdings Inc", "Citizens Financial Group Inc", 
"Church & Dwight Co Inc", "CH Robinson Worldwide Inc", "Charter Communications Inc", 
"Cigna Corp", "Cincinnati Financial Corp", "Colgate-Palmolive Co", 
"Clorox Co", "Comerica Inc", "Comcast Corp", "CME Group Inc", 
"Chipotle Mexican Grill Inc", "Cummins Inc", "CMS Energy Corp", 
"Centene Corp", "CenterPoint Energy Inc", "Capital One Financial Corp", 
"Cabot Oil & Gas Corp", "Cooper Companies Inc", "ConocoPhillips", 
"Costco Wholesale Corp", "Campbell Soup Co", "Copart Inc", "Salesforce.Com Inc", 
"Cisco Systems Inc", "CSX Corp", "Cintas Corp", "Catalent Inc", 
"Cognizant Technology Solutions Corp", "Corteva Inc", "Citrix Systems Inc", 
"CVS Health Corp", "Chevron Corp", "Concho Resources Inc", "Dominion Energy Inc", 
"Delta Air Lines Inc", "Dupont De Nemours Inc", "Deere & Co", 
"Discover Financial Services", "Dollar General Corp", "Quest Diagnostics Inc", 
"D.R. Horton Inc", "Danaher Corp", "Walt Disney Co", "Discovery Inc", 
"Discovery Inc", "DISH Network Corp", "Digital Realty Trust Inc", 
"Dollar Tree Inc", "Dover Corp", "Dow Inc", "Domino's Pizza Inc", 
"Duke Realty Corp", "Darden Restaurants Inc", "DTE Energy Co", 
"Duke Energy Corp", "DaVita Inc", "Devon Energy Corp", "DXC Technology Co", 
"DexCom Inc", "Electronic Arts Inc", "eBay Inc", "Ecolab Inc", 
"Consolidated Edison Inc", "Equifax Inc", "Edison International", 
"Estee Lauder Companies Inc", "Eastman Chemical Co", "Emerson Electric Co", 
"EOG Resources Inc", "Equinix Inc", "Equity Residential", "Eversource Energy", 
"Essex Property Trust Inc", "Eaton Corporation PLC", "Entergy Corp", 
"ETSY Inc", "Evergy Inc", "Edwards Lifesciences Corp", "Exelon Corp", 
"Expeditors International of Washington Inc", "Expedia Group Inc", 
"Extra Space Storage Inc", "Ford Motor Co", "Diamondback Energy Inc", 
"Fastenal Co", "Facebook Inc", "Fortune Brands Home & Security Inc", 
"Freeport-McMoRan Inc", "FedEx Corp", "FirstEnergy Corp", "F5 Networks Inc", 
"Fidelity National Information Services Inc", "Fiserv Inc", "Fifth Third Bancorp", 
"FLIR Systems Inc", "Flowserve Corp", "Fleetcor Technologies Inc", 
"FMC Corp", "Fox Corp", "Fox Corp", "First Republic Bank", "Federal Realty Investment Trust", 
"TechnipFMC PLC", "Fortinet Inc", "Fortive Corp", "General Dynamics Corp", 
"General Electric Co", "Gilead Sciences Inc", "General Mills Inc", 
"Globe Life Inc", "Corning Inc", "General Motors Co", "Alphabet Inc", 
"Alphabet Inc", "Genuine Parts Co", "Global Payments Inc", "Gap Inc", 
"Garmin Ltd", "Goldman Sachs Group Inc", "W W Grainger Inc", 
"Halliburton Co", "Hasbro Inc", "Huntington Bancshares Inc", 
"HanesBrands Inc", "HCA Healthcare Inc", "Home Depot Inc", "Hess Corp", 
"HollyFrontier Corp", "Hartford Financial Services Group Inc", 
"Huntington Ingalls Industries Inc", "Hilton Worldwide Holdings Inc", 
"Hologic Inc", "Honeywell International Inc", "Hewlett Packard Enterprise Co", 
"HP Inc", "Hormel Foods Corp", "Henry Schein Inc", "Host Hotels & Resorts Inc", 
"Hershey Co", "Humana Inc", "Howmet Aerospace Inc", "International Business Machines Corp", 
"Intercontinental Exchange Inc", "IDEXX Laboratories Inc", "IDEX Corp", 
"International Flavors & Fragrances Inc", "Illumina Inc", "Incyte Corp", 
"IHS Markit Ltd", "Intel Corp", "Intuit Inc", "International Paper Co", 
"Interpublic Group of Companies Inc", "IPG Photonics Corp", "IQVIA Holdings Inc", 
"Ingersoll Rand Inc", "Iron Mountain Inc", "Intuitive Surgical Inc", 
"Gartner Inc", "Illinois Tool Works Inc", "Invesco Ltd", "Jacobs Engineering Group Inc", 
"J B Hunt Transport Services Inc", "Johnson Controls International PLC", 
"Jack Henry & Associates Inc", "Johnson & Johnson", "Juniper Networks Inc", 
"JPMorgan Chase & Co", "Kellogg Co", "KeyCorp", "Keysight Technologies Inc", 
"Kraft Heinz Co", "Kimco Realty Corp", "KLA Corp", "Kimberly-Clark Corp", 
"Kinder Morgan Inc", "Carmax Inc", "Coca-Cola Co", "Kroger Co", 
"Kansas City Southern", "Loews Corp", "L Brands Inc", "Leidos Holdings Inc", 
"Leggett & Platt Inc", "Lennar Corp", "Laboratory Corporation of America Holdings", 
"L3harris Technologies Inc", "Linde PLC", "LKQ Corp", "Eli Lilly and Co", 
"Lockheed Martin Corp", "Lincoln National Corp", "Alliant Energy Corp", 
"Lowe's Companies Inc", "Lam Research Corp", "Centurylink Inc", 
"Southwest Airlines Co", "Las Vegas Sands Corp", "Lamb Weston Holdings Inc", 
"LyondellBasell Industries NV", "Live Nation Entertainment Inc", 
"Mastercard Inc", "Mid-America Apartment Communities Inc", "Marriott International Inc", 
"Masco Corp", "Mcdonald's Corp", "Microchip Technology Inc", 
"Mckesson Corp", "Moody's Corp", "Mondelez International Inc", 
"Medtronic PLC", "MetLife Inc", "MGM Resorts International", 
"Mohawk Industries Inc", "McCormick & Company Inc", "Marketaxess Holdings Inc", 
"Martin Marietta Materials Inc", "Marsh & McLennan Companies Inc", 
"3M Co", "Monster Beverage Corp", "Altria Group Inc", "Mosaic Co", 
"Marathon Petroleum Corp", "Merck & Co Inc", "Marathon Oil Corp", 
"Morgan Stanley", "MSCI Inc", "Microsoft Corp", "Motorola Solutions Inc", 
"M&T Bank Corp", "Mettler-Toledo International Inc", "Micron Technology Inc", 
"Maxim Integrated Products Inc", "Norwegian Cruise Line Holdings Ltd", 
"Nasdaq Inc", "Nextera Energy Inc", "Newmont Corporation", "Netflix Inc", 
"NiSource Inc", "Nike Inc", "NortonLifeLock Inc", "Nielsen Holdings PLC", 
"Northrop Grumman Corp", "National Oilwell Varco Inc", "ServiceNow Inc", 
"NRG Energy Inc", "Norfolk Southern Corp", "NetApp Inc", "Northern Trust Corp", 
"Nucor Corp", "NVIDIA Corp", "NVR Inc", "Newell Brands Inc", 
"News Corp", "News Corp", "Realty Income Corp", "Old Dominion Freight Line Inc", 
"ONEOK Inc", "Omnicom Group Inc", "Oracle Corp", "O'Reilly Automotive Inc", 
"Otis Worldwide Corp", "Occidental Petroleum Corp", "Paycom Software Inc", 
"Paychex Inc", "People's United Financial Inc", "Paccar Inc", 
"Healthpeak Properties Inc", "Public Service Enterprise Group Inc", 
"PepsiCo Inc", "Pfizer Inc", "Principal Financial Group Inc", 
"Procter & Gamble Co", "Progressive Corp", "Parker-Hannifin Corp", 
"Pultegroup Inc", "Packaging Corp of America", "PerkinElmer Inc", 
"Prologis Inc", "Philip Morris International Inc", "PNC Financial Services Group Inc", 
"Pentair PLC", "Pinnacle West Capital Corp", "Pool Corp", "PPG Industries Inc", 
"PPL Corp", "Perrigo Company PLC", "Prudential Financial Inc", 
"Public Storage", "Phillips 66", "PVH Corp", "Quanta Services Inc", 
"Pioneer Natural Resources Co", "PayPal Holdings Inc", "Qualcomm Inc", 
"Qorvo Inc", "Royal Caribbean Cruises Ltd", "Everest Re Group Ltd", 
"Regency Centers Corp", "Regeneron Pharmaceuticals Inc", "Regions Financial Corp", 
"Robert Half International Inc", "Raymond James Financial Inc", 
"Ralph Lauren Corp", "Resmed Inc", "Rockwell Automation Inc", 
"Rollins Inc", "Roper Technologies Inc", "Ross Stores Inc", "Republic Services Inc", 
"Raytheon Technologies Corp", "SBA Communications Corp", "Starbucks Corp", 
"Charles Schwab Corp", "Sealed Air Corp", "Sherwin-Williams Co", 
"SVB Financial Group", "J M Smucker Co", "Schlumberger NV", "SL Green Realty Corp", 
"Snap-On Inc", "Synopsys Inc", "Southern Co", "Simon Property Group Inc", 
"S&P Global Inc", "Sempra Energy", "Steris plc", "State Street Corp", 
"Seagate Technology PLC", "Constellation Brands Inc", "Stanley Black & Decker Inc", 
"Skyworks Solutions Inc", "Synchrony Financial", "Stryker Corp", 
"Sysco Corp", "AT&T Inc", "Molson Coors Beverage Co", "TransDigm Group Inc", 
"Teledyne Technologies Inc", "TE Connectivity Ltd", "Teradyne Inc", 
"Truist Financial Corp", "Teleflex Inc", "Target Corp", "Tiffany & Co", 
"TJX Companies Inc", "Thermo Fisher Scientific Inc", "T-Mobile US Inc", 
"Tapestry Inc", "T. Rowe Price Group Inc", "Travelers Companies Inc", 
"Tractor Supply Co", "Tyson Foods Inc", "Trane Technologies PLC", 
"Take-Two Interactive Software Inc", "Twitter Inc", "Texas Instruments Inc", 
"Textron Inc", "Tyler Technologies Inc", "Under Armour Inc", 
"Under Armour Inc", "United Airlines Holdings Inc", "UDR Inc", 
"Universal Health Services Inc", "Ulta Beauty Inc", "UnitedHealth Group Inc", 
"Unum Group", "Union Pacific Corp", "United Parcel Service Inc", 
"United Rentals Inc", "U.S. Bancorp", "Visa Inc", "Varian Medical Systems Inc", 
"VF Corp", "ViacomCBS Inc", "Valero Energy Corp", "Vulcan Materials Co", 
"Vornado Realty Trust", "Vontier Corp", "Verisk Analytics Inc", 
"Verisign Inc", "Vertex Pharmaceuticals Inc", "Ventas Inc", "Mylan NV", 
"Verizon Communications Inc", "Westinghouse Air Brake Technologies Corp", 
"Waters Corp", "Walgreens Boots Alliance Inc", "Western Digital Corp", 
"WEC Energy Group Inc", "Welltower Inc", "Wells Fargo & Co", 
"Whirlpool Corp", "Willis Towers Watson PLC", "Waste Management Inc", 
"Williams Companies Inc", "Walmart Inc", "W. R. Berkley Corp", 
"Westrock Co", "West Pharmaceutical Services Inc", "Western Union Co", 
"Weyerhaeuser Co", "Wynn Resorts Ltd", "Xcel Energy Inc", "Xilinx Inc", 
"Exxon Mobil Corp", "DENTSPLY SIRONA Inc", "Xerox Holdings Corp", 
"Xylem Inc", "Yum! Brands Inc", "Zimmer Biomet Holdings Inc", 
"Zebra Technologies Corp", "Zions Bancorporation NA", "Zoetis Inc"
)
