S <-
c(.SPX = ".SPX", A = "A", AAL.O = "AAL.O", AAP = "AAP", AAPL.O = "AAPL.O", 
ABBV.K = "ABBV.K", ABC = "ABC", ABMD.O = "ABMD.O", ABT = "ABT", 
ACN = "ACN", ADBE.O = "ADBE.O", ADI.O = "ADI.O", ADM = "ADM", 
ADP.O = "ADP.O", ADSK.O = "ADSK.O", AEE = "AEE", AEP.O = "AEP.O", 
AES = "AES", AFL = "AFL", AIG = "AIG", AIV = "AIV", AIZ = "AIZ", 
AJG = "AJG", AKAM.O = "AKAM.O", ALB = "ALB", ALGN.O = "ALGN.O", 
ALK = "ALK", ALL = "ALL", ALLE.K = "ALLE.K", ALXN.O = "ALXN.O", 
AMAT.O = "AMAT.O", AMCR.K = "AMCR.K", AMD.O = "AMD.O", AME = "AME", 
AMGN.O = "AMGN.O", AMP = "AMP", AMT = "AMT", AMZN.O = "AMZN.O", 
ANET.K = "ANET.K", ANSS.O = "ANSS.O", ANTM.K = "ANTM.K", AON = "AON", 
AOS = "AOS", APA.O = "APA.O", APD = "APD", APH = "APH", APTV.K = "APTV.K", 
ARE = "ARE", ATO = "ATO", ATVI.O = "ATVI.O", AVB = "AVB", AVGO.O = "AVGO.O", 
AVY = "AVY", AWK = "AWK", AXP = "AXP", AZO = "AZO", BA = "BA", 
BAC = "BAC", BAX = "BAX", BBY = "BBY", BDX = "BDX", BEN = "BEN", 
BFb = "BFb", BIIB.O = "BIIB.O", BIO = "BIO", BK = "BK", BKNG.O = "BKNG.O", 
BKR = "BKR", BLK = "BLK", BLL = "BLL", BMY = "BMY", BR = "BR", 
BRKb = "BRKb", BSX = "BSX", BWA = "BWA", BXP = "BXP", C = "C", 
CAG = "CAG", CAH = "CAH", CARR.K = "CARR.K", CAT = "CAT", CB = "CB", 
CBOE.K = "CBOE.K", CBRE.K = "CBRE.K", CCI = "CCI", CCL = "CCL", 
CDNS.O = "CDNS.O", CDW.O = "CDW.O", CE = "CE", CERN.O = "CERN.O", 
CF = "CF", CFG = "CFG", CHD = "CHD", CHRW.O = "CHRW.O", CHTR.O = "CHTR.O", 
CI = "CI", CINF.O = "CINF.O", CL = "CL", CLX = "CLX", CMA = "CMA", 
CMCSA.O = "CMCSA.O", CME.O = "CME.O", CMG = "CMG", CMI = "CMI", 
CMS = "CMS", CNC = "CNC", CNP = "CNP", COF = "COF", COG = "COG", 
COO = "COO", COP = "COP", COST.O = "COST.O", CPB = "CPB", CPRT.O = "CPRT.O", 
CRM = "CRM", CSCO.O = "CSCO.O", CSX.O = "CSX.O", CTAS.O = "CTAS.O", 
CTLT.K = "CTLT.K", CTSH.O = "CTSH.O", CTVA.K = "CTVA.K", CTXS.O = "CTXS.O", 
CVS = "CVS", CVX = "CVX", CXO = "CXO", D = "D", DAL = "DAL", 
DD = "DD", DE = "DE", DFS = "DFS", DG = "DG", DGX = "DGX", DHI = "DHI", 
DHR = "DHR", DIS = "DIS", DISCA.O = "DISCA.O", DISCK.O = "DISCK.O", 
DISH.O = "DISH.O", DLR = "DLR", DLTR.O = "DLTR.O", DOV = "DOV", 
DOW = "DOW", DPZ = "DPZ", DRE = "DRE", DRI = "DRI", DTE = "DTE", 
DUK = "DUK", DVA = "DVA", DVN = "DVN", DXC = "DXC", DXCM.O = "DXCM.O", 
EA.O = "EA.O", EBAY.O = "EBAY.O", ECL = "ECL", ED = "ED", EFX = "EFX", 
EIX = "EIX", EL = "EL", EMN = "EMN", EMR = "EMR", EOG = "EOG", 
EQIX.O = "EQIX.O", EQR = "EQR", ES = "ES", ESS = "ESS", ETN = "ETN", 
ETR = "ETR", ETSY.O = "ETSY.O", EVRG.K = "EVRG.K", EW = "EW", 
EXC.O = "EXC.O", EXPD.O = "EXPD.O", EXPE.O = "EXPE.O", EXR = "EXR", 
F = "F", FANG.O = "FANG.O", FAST.O = "FAST.O", FB.O = "FB.O", 
FBHS.K = "FBHS.K", FCX = "FCX", FDX = "FDX", FE = "FE", FFIV.O = "FFIV.O", 
FIS = "FIS", FISV.O = "FISV.O", FITB.O = "FITB.O", FLIR.O = "FLIR.O", 
FLS = "FLS", FLT = "FLT", FMC = "FMC", FOX.O = "FOX.O", FOXA.O = "FOXA.O", 
FRC = "FRC", FRT = "FRT", FTI = "FTI", FTNT.O = "FTNT.O", FTV = "FTV", 
GD = "GD", GE = "GE", GILD.O = "GILD.O", GIS = "GIS", GL = "GL", 
GLW = "GLW", GM = "GM", GOOG.O = "GOOG.O", GOOGL.O = "GOOGL.O", 
GPC = "GPC", GPN = "GPN", GPS = "GPS", GRMN.O = "GRMN.O", GS = "GS", 
GWW = "GWW", HAL = "HAL", HAS.O = "HAS.O", HBAN.O = "HBAN.O", 
HBI = "HBI", HCA = "HCA", HD = "HD", HES = "HES", HFC = "HFC", 
HIG = "HIG", HII = "HII", HLT = "HLT", HOLX.O = "HOLX.O", HON = "HON", 
HPE = "HPE", HPQ = "HPQ", HRL = "HRL", HSIC.O = "HSIC.O", HST.O = "HST.O", 
HSY = "HSY", HUM = "HUM", HWM = "HWM", IBM = "IBM", ICE = "ICE", 
IDXX.O = "IDXX.O", IEX = "IEX", IFF = "IFF", ILMN.O = "ILMN.O", 
INCY.O = "INCY.O", INFO.K = "INFO.K", INTC.O = "INTC.O", INTU.O = "INTU.O", 
IP = "IP", IPG = "IPG", IPGP.O = "IPGP.O", IQV = "IQV", IR = "IR", 
IRM = "IRM", ISRG.O = "ISRG.O", IT = "IT", ITW = "ITW", IVZ = "IVZ", 
J = "J", JBHT.O = "JBHT.O", JCI = "JCI", JKHY.O = "JKHY.O", JNJ = "JNJ", 
JNPR.K = "JNPR.K", JPM = "JPM", K = "K", KEY = "KEY", KEYS.K = "KEYS.K", 
KHC.O = "KHC.O", KIM = "KIM", KLAC.O = "KLAC.O", KMB = "KMB", 
KMI = "KMI", KMX = "KMX", KO = "KO", KR = "KR", KSU = "KSU", 
L = "L", LB = "LB", LDOS.K = "LDOS.K", LEG = "LEG", LEN = "LEN", 
LH = "LH", LHX = "LHX", LIN = "LIN", LKQ.O = "LKQ.O", LLY = "LLY", 
LMT = "LMT", LNC = "LNC", LNT.O = "LNT.O", LOW = "LOW", LRCX.O = "LRCX.O", 
LUMN.K = "LUMN.K", LUV = "LUV", LVS = "LVS", LW = "LW", LYB = "LYB", 
LYV = "LYV", MA = "MA", MAA = "MAA", MAR.O = "MAR.O", MAS = "MAS", 
MCD = "MCD", MCHP.O = "MCHP.O", MCK = "MCK", MCO = "MCO", MDLZ.O = "MDLZ.O", 
MDT = "MDT", MET = "MET", MGM = "MGM", MHK = "MHK", MKC = "MKC", 
MKTX.O = "MKTX.O", MLM = "MLM", MMC = "MMC", MMM = "MMM", MNST.O = "MNST.O", 
MO = "MO", MOS = "MOS", MPC = "MPC", MRK = "MRK", MRO = "MRO", 
MS = "MS", MSCI.K = "MSCI.K", MSFT.O = "MSFT.O", MSI = "MSI", 
MTB = "MTB", MTD = "MTD", MU.O = "MU.O", MXIM.O = "MXIM.O", NCLH.K = "NCLH.K", 
NDAQ.O = "NDAQ.O", NEE = "NEE", NEM = "NEM", NFLX.O = "NFLX.O", 
NI = "NI", NKE = "NKE", NLOK.O = "NLOK.O", NLSN.K = "NLSN.K", 
NOC = "NOC", NOV = "NOV", NOW = "NOW", NRG = "NRG", NSC = "NSC", 
NTAP.O = "NTAP.O", NTRS.O = "NTRS.O", NUE = "NUE", NVDA.O = "NVDA.O", 
NVR = "NVR", NWL.O = "NWL.O", NWS.O = "NWS.O", NWSA.O = "NWSA.O", 
O = "O", ODFL.O = "ODFL.O", OKE = "OKE", OMC = "OMC", ORCL.K = "ORCL.K", 
ORLY.O = "ORLY.O", OTIS.K = "OTIS.K", OXY = "OXY", PAYC.K = "PAYC.K", 
PAYX.O = "PAYX.O", PBCT.O = "PBCT.O", PCAR.O = "PCAR.O", PEAK.K = "PEAK.K", 
PEG = "PEG", PEP.O = "PEP.O", PFE = "PFE", PFG.O = "PFG.O", PG = "PG", 
PGR = "PGR", PH = "PH", PHM = "PHM", PKG = "PKG", PKI = "PKI", 
PLD = "PLD", PM = "PM", PNC = "PNC", PNR = "PNR", PNW = "PNW", 
POOL.O = "POOL.O", PPG = "PPG", PPL = "PPL", PRGO.K = "PRGO.K", 
PRU = "PRU", PSA = "PSA", PSX = "PSX", PVH = "PVH", PWR = "PWR", 
PXD = "PXD", PYPL.O = "PYPL.O", QCOM.O = "QCOM.O", QRVO.O = "QRVO.O", 
RCL = "RCL", RE = "RE", REG.O = "REG.O", REGN.O = "REGN.O", RF = "RF", 
RHI = "RHI", RJF = "RJF", RL = "RL", RMD = "RMD", ROK = "ROK", 
ROL = "ROL", ROP = "ROP", ROST.O = "ROST.O", RSG = "RSG", RTX = "RTX", 
SBAC.O = "SBAC.O", SBUX.O = "SBUX.O", SCHW.K = "SCHW.K", SEE = "SEE", 
SHW = "SHW", SIVB.O = "SIVB.O", SJM = "SJM", SLB = "SLB", SLG = "SLG", 
SNA = "SNA", SNPS.O = "SNPS.O", SO = "SO", SPG = "SPG", SPGI.K = "SPGI.K", 
SRE = "SRE", STE = "STE", STT = "STT", STX.O = "STX.O", STZ = "STZ", 
SWK = "SWK", SWKS.O = "SWKS.O", SYF = "SYF", SYK = "SYK", SYY = "SYY", 
T = "T", TAP = "TAP", TDG = "TDG", TDY = "TDY", TEL = "TEL", 
TER.O = "TER.O", TFC = "TFC", TFX = "TFX", TGT = "TGT", TIF = "TIF", 
TJX = "TJX", TMO = "TMO", TMUS.O = "TMUS.O", TPR = "TPR", TROW.O = "TROW.O", 
TRV = "TRV", TSCO.O = "TSCO.O", TSN = "TSN", TT = "TT", TTWO.O = "TTWO.O", 
TWTR.K = "TWTR.K", TXN.O = "TXN.O", TXT = "TXT", TYL = "TYL", 
UA = "UA", UAA = "UAA", UAL.O = "UAL.O", UDR = "UDR", UHS = "UHS", 
ULTA.O = "ULTA.O", UNH = "UNH", UNM = "UNM", UNP = "UNP", UPS = "UPS", 
URI = "URI", USB = "USB", V = "V", VAR = "VAR", VFC = "VFC", 
VIAC.O = "VIAC.O", VLO = "VLO", VMC = "VMC", VNO = "VNO", VNT = "VNT", 
VRSK.O = "VRSK.O", VRSN.O = "VRSN.O", VRTX.O = "VRTX.O", VTR = "VTR", 
VTRS.O = "VTRS.O", VZ = "VZ", WAB = "WAB", WAT = "WAT", WBA.O = "WBA.O", 
WDC.O = "WDC.O", WEC = "WEC", WELL.K = "WELL.K", WFC = "WFC", 
WHR = "WHR", WLTW.O = "WLTW.O", WM = "WM", WMB = "WMB", WMT = "WMT", 
WRB = "WRB", WRK = "WRK", WST = "WST", WU = "WU", WY = "WY", 
WYNN.O = "WYNN.O", XEL.O = "XEL.O", XLNX.O = "XLNX.O", XOM = "XOM", 
XRAY.O = "XRAY.O", XRX = "XRX", XYL = "XYL", YUM = "YUM", ZBH = "ZBH", 
ZBRA.O = "ZBRA.O", ZION.O = "ZION.O", ZTS = "ZTS")
