S <-
c("RIC", "AAPL.O", "MSFT.O", "AMZN.O", "GOOG.O", "GOOGL.O", "FB.O", 
"TSLA.O", "BRKb", "JPM", "V", "JNJ", "WMT", "MA", "UNH", "DIS", 
"PG", "NVDA.O", "BAC", "HD", "PYPL.O", "INTC.O", "CMCSA.O", "NFLX.O", 
"VZ", "XOM", "KO", "ADBE.O", "NKE", "T", "ABT", "CSCO.O", "CRM", 
"PFE", "CVX", "ORCL.K", "MRK", "PEP.O", "AVGO.O", "ABBV.K", "TMO", 
"ACN", "LLY", "MCD", "TXN.O", "WFC", "DHR", "MDT", "TMUS.O", 
"COST.O", "QCOM.O", "MS", "C", "HON", "NEE", "AMGN.O", "BA", 
"BMY", "LIN", "UNP", "CHTR.O", "UPS", "PM", "LOW", "SBUX.O", 
"SCHW.K", "CAT", "IBM", "RTX", "GS", "DE", "GE", "BLK", "AXP", 
"MMM", "AMAT.O", "INTU.O", "AMT", "EL", "LMT", "MU.O", "AMD.O", 
"CVS", "TGT", "MO", "NOW", "BKNG.O", "FIS", "SYK", "ANTM.K", 
"ISRG.O", "SPGI.K", "CI", "MDLZ.O", "FISV.O", "GILD.O", "GM", 
"USB", "ADP.O", "PLD", "LRCX.O", "TJX", "TFC", "ZTS", "CCI", 
"DUK", "PNC", "CME.O", "CB", "CSX.O", "ATVI.O", "FDX", "COP", 
"BDX", "ITW", "CL", "NSC", "SHW", "SO", "ICE", "HCA", "APD", 
"ILMN.O", "EQIX.O", "D", "ECL", "MMC", "GPN", "ADSK.O", "VIAC.O", 
"COF", "VRTX.O", "ADI.O", "MCO", "PGR", "NXPI.O", "ETN", "BSX", 
"WM", "NOC", "EMR", "HUM", "MET", "TWTR.K", "AON", "REGN.O", 
"GD", "EW", "NEM", "F", "KHC.O", "MNST.O", "DG", "FCX", "MAR.O", 
"KLAC.O", "KMB", "LVS", "DOW", "WBA.O", "STZ", "ROP", "PSA", 
"JCI", "AEP.O", "EXC.O", "IDXX.O", "ROST.O", "BAX", "ALGN.O", 
"EBAY.O", "TEL", "CMG", "BIIB.O", "EOG", "CTSH.O", "MCHP.O", 
"LHX", "DD", "INFO.K", "SYY", "PH", "DLR", "SRE", "BK", "AIG", 
"TROW.O", "EA.O", "TT", "CMI", "APTV.K", "APH", "GIS", "SLB", 
"CNC", "A", "TRV", "HPQ", "SPG", "IQV", "SNPS.O", "CDNS.O", "KMI", 
"XEL.O", "PRU", "DXCM.O", "CARR.K", "CTAS.O", "PPG", "MSCI.K", 
"PAYX.O", "PSX", "MPC", "CTVA.K", "PXD", "ORLY.O", "AFL", "LUV", 
"ALL", "IFF", "LYB", "ALXN.O", "HLT", "BFb", "HSY", "ZBH", "YUM", 
"DISCA.O", "DISCK.O", "TDG", "PCAR.O", "MSI", "ADM", "SWK", "RSG", 
"GLW", "DHI", "ROK", "XLNX.O", "MCK", "SBAC.O", "VFC", "BBY", 
"WELL.K", "PEG", "AZO", "WEC", "DAL", "LEN", "ES", "ANSS.O", 
"SWKS.O", "VRSK.O", "OTIS.K", "FTNT.O", "FRC", "VLO", "WLTW.O", 
"DFS", "AME", "BLL", "CCL", "WMB", "STT", "KR", "RMD", "ETSY.O", 
"FAST.O", "ODFL.O", "TSN", "EQR", "HRL", "AWK", "MTD", "FITB.O", 
"AMP", "SIVB.O", "AVB", "DLTR.O", "CPRT.O", "CBRE.K", "KEYS.K", 
"WY", "ED", "DTE", "OXY", "ZBRA.O", "NDAQ.O", "CLX", "EXPE.O", 
"GRMN.O", "HIG", "FOXA.O", "FOX.O", "AJG", "MXIM.O", "O", "MKC", 
"LH", "ABC", "FTV", "FLT", "ARE", "SYF", "BKR", "PAYC.K", "KSU", 
"EIX", "VRSN.O", "CDW.O", "CERN.O", "PPL", "ANET.K", "URI", "EFX", 
"RCL", "K", "KMX", "OKE", "CHD", "VMC", "WST", "GWW", "HES", 
"NTRS.O", "AEE", "IP", "VTR", "ENPH.O", "NUE", "TSCO.O", "WDC.O", 
"TTWO.O", "MKTX.O", "QRVO.O", "IR", "MLM", "ETR", "RF", "DOV", 
"HPE", "GNRC.K", "DISH.O", "TER.O", "MTB", "COO", "HOLX.O", "FE", 
"KEY", "TFX", "CAG", "HAL", "MGM", "CTLT.K", "XYL", "CFG", "ESS", 
"TRMB.O", "DRI", "LYV", "AMCR.K", "CZR.O", "INCY.O", "PENN.O", 
"CMS", "ULTA.O", "EXR", "UAL.O", "EXPD.O", "VTRS.O", "PEAK.K", 
"AES", "BIO", "ALB", "TYL", "BR", "CTXS.O", "CAH", "CINF.O", 
"WAT", "STX.O", "ROL", "DGX", "GPC", "MAA", "JBHT.O", "NVR", 
"AKAM.O", "RJF", "OMC", "VAR", "CE", "IT", "LB", "BXP", "STE", 
"J", "PFG.O", "DRE", "HBAN.O", "MPWR.O", "CPB", "NTAP.O", "NWSA.O", 
"NWS.O", "IEX", "LUMN.K", "AVY", "DVN", "MAS", "DPZ", "EMN", 
"BEN", "WYNN.O", "TDY", "PKI", "AAL.O", "WAB", "FMC", "SJM", 
"POOL.O", "L", "ABMD.O", "WHR", "EVRG.K", "LDOS.K", "HAS.O", 
"LNT.O", "HWM", "XRAY.O", "WRB", "UDR", "PHM", "WRK", "MHK", 
"CHRW.O", "LKQ.O", "NLOK.O", "FFIV.O", "FANG.O", "PKG", "FBHS.K", 
"CNP", "HST.O", "TXT", "AAP", "SNA", "DVA", "MOS", "JKHY.O", 
"ATO", "LNC", "TPR", "LW", "PWR", "UHS", "GL", "IPG", "IPGP.O", 
"CBOE.K", "IVZ", "ALLE.K", "NWL.O", "TAP", "AOS", "BWA", "IRM", 
"GPS", "WU", "PNR", "NCLH.K", "RE", "CF", "CMA", "UAA", "UA", 
"REG.O", "HSIC.O", "NI", "NLSN.K", "PNW", "ZION.O", "NRG", "VNO", 
"AIZ", "RHI", "RL", "JNPR.K", "ALK", "MRO", "KIM", "HII", "FRT", 
"PBCT.O", "FLIR.O", "COG", "SEE", "APA.O", "PVH", "DXC", "HBI", 
"LEG", "HFC", "PRGO.K", "UNM", "NOV", ".SPX")
