S <-
c(`S&P 500 Index` = ".SPX", `Agilent Technologies Inc` = "A", 
`American Airlines Group Inc` = "AAL.O", `Advance Auto Parts Inc` = "AAP", 
`Apple Inc` = "AAPL.O", `Abbvie Inc` = "ABBV.K", `Amerisourcebergen Corp` = "ABC", 
`ABIOMED Inc` = "ABMD.O", `Abbott Laboratories` = "ABT", `Accenture PLC` = "ACN", 
`Adobe Inc` = "ADBE.O", `Analog Devices Inc` = "ADI.O", `Archer-Daniels-Midland Co` = "ADM", 
`Automatic Data Processing Inc` = "ADP.O", `Autodesk Inc` = "ADSK.O", 
`Ameren Corp` = "AEE", `American Electric Power Company Inc` = "AEP.O", 
`AES Corp` = "AES", `Aflac Inc` = "AFL", `American International Group Inc` = "AIG", 
`Apartment Investment and Management Co` = "AIV", `Assurant Inc` = "AIZ", 
`Arthur J Gallagher & Co` = "AJG", `Akamai Technologies Inc` = "AKAM.O", 
`Albemarle Corp` = "ALB", `Align Technology Inc` = "ALGN.O", 
`Alaska Air Group Inc` = "ALK", `Allstate Corp` = "ALL", `Allegion PLC` = "ALLE.K", 
`Alexion Pharmaceuticals Inc` = "ALXN.O", `Applied Materials Inc` = "AMAT.O", 
`Amcor PLC` = "AMCR.K", `Advanced Micro Devices Inc` = "AMD.O", 
`AMETEK Inc` = "AME", `Amgen Inc` = "AMGN.O", `Ameriprise Financial Inc` = "AMP", 
`American Tower Corp` = "AMT", `Amazon.com Inc` = "AMZN.O", `Arista Networks Inc` = "ANET.K", 
`ANSYS Inc` = "ANSS.O", `Anthem Inc` = "ANTM.K", `Aon PLC` = "AON", 
`A. O. Smith Corp` = "AOS", `Apache Corp` = "APA.O", `Air Products and Chemicals Inc` = "APD", 
`Amphenol Corp` = "APH", `Aptiv PLC` = "APTV.K", `Alexandria Real Estate Equities Inc` = "ARE", 
`Atmos Energy Corp` = "ATO", `Activision Blizzard Inc` = "ATVI.O", 
`Avalonbay Communities Inc` = "AVB", `Broadcom Inc` = "AVGO.O", 
`Avery Dennison Corp` = "AVY", `American Water Works Company Inc` = "AWK", 
`American Express Co` = "AXP", `Autozone Inc` = "AZO", `Boeing Co` = "BA", 
`Bank of America Corp` = "BAC", `Baxter International Inc` = "BAX", 
`Best Buy Co Inc` = "BBY", `Becton Dickinson and Co` = "BDX", 
`Franklin Resources Inc` = "BEN", `Brown-Forman Corp` = "BFb", 
`Biogen Inc` = "BIIB.O", `Bio Rad Laboratories Inc` = "BIO", 
`Bank of New York Mellon Corp` = "BK", `Booking Holdings Inc` = "BKNG.O", 
`Baker Hughes Co` = "BKR", `BlackRock Inc` = "BLK", `Ball Corp` = "BLL", 
`Bristol-Myers Squibb Co` = "BMY", `Broadridge Financial Solutions Inc` = "BR", 
`Berkshire Hathaway Inc` = "BRKb", `Boston Scientific Corp` = "BSX", 
`Borgwarner Inc` = "BWA", `Boston Properties Inc` = "BXP", `Citigroup Inc` = "C", 
`Conagra Brands Inc` = "CAG", `Cardinal Health Inc` = "CAH", 
`Carrier Global Corp` = "CARR.K", `Caterpillar Inc` = "CAT", 
`Chubb Ltd` = "CB", `Cboe Global Markets Inc` = "CBOE.K", `CBRE Group Inc` = "CBRE.K", 
`Crown Castle International Corp` = "CCI", `Carnival Corp` = "CCL", 
`Cadence Design Systems Inc` = "CDNS.O", `CDW Corp` = "CDW.O", 
`Celanese Corp` = "CE", `Cerner Corp` = "CERN.O", `CF Industries Holdings Inc` = "CF", 
`Citizens Financial Group Inc` = "CFG", `Church & Dwight Co Inc` = "CHD", 
`CH Robinson Worldwide Inc` = "CHRW.O", `Charter Communications Inc` = "CHTR.O", 
`Cigna Corp` = "CI", `Cincinnati Financial Corp` = "CINF.O", 
`Colgate-Palmolive Co` = "CL", `Clorox Co` = "CLX", `Comerica Inc` = "CMA", 
`Comcast Corp` = "CMCSA.O", `CME Group Inc` = "CME.O", `Chipotle Mexican Grill Inc` = "CMG", 
`Cummins Inc` = "CMI", `CMS Energy Corp` = "CMS", `Centene Corp` = "CNC", 
`CenterPoint Energy Inc` = "CNP", `Capital One Financial Corp` = "COF", 
`Cabot Oil & Gas Corp` = "COG", `Cooper Companies Inc` = "COO", 
ConocoPhillips = "COP", `Costco Wholesale Corp` = "COST.O", `Campbell Soup Co` = "CPB", 
`Copart Inc` = "CPRT.O", `Salesforce.Com Inc` = "CRM", `Cisco Systems Inc` = "CSCO.O", 
`CSX Corp` = "CSX.O", `Cintas Corp` = "CTAS.O", `Catalent Inc` = "CTLT.K", 
`Cognizant Technology Solutions Corp` = "CTSH.O", `Corteva Inc` = "CTVA.K", 
`Citrix Systems Inc` = "CTXS.O", `CVS Health Corp` = "CVS", `Chevron Corp` = "CVX", 
`Concho Resources Inc` = "CXO", `Dominion Energy Inc` = "D", 
`Delta Air Lines Inc` = "DAL", `Dupont De Nemours Inc` = "DD", 
`Deere & Co` = "DE", `Discover Financial Services` = "DFS", `Dollar General Corp` = "DG", 
`Quest Diagnostics Inc` = "DGX", `D.R. Horton Inc` = "DHI", `Danaher Corp` = "DHR", 
`Walt Disney Co` = "DIS", `Discovery Inc` = "DISCA.O", `Discovery Inc` = "DISCK.O", 
`DISH Network Corp` = "DISH.O", `Digital Realty Trust Inc` = "DLR", 
`Dollar Tree Inc` = "DLTR.O", `Dover Corp` = "DOV", `Dow Inc` = "DOW", 
`Domino's Pizza Inc` = "DPZ", `Duke Realty Corp` = "DRE", `Darden Restaurants Inc` = "DRI", 
`DTE Energy Co` = "DTE", `Duke Energy Corp` = "DUK", `DaVita Inc` = "DVA", 
`Devon Energy Corp` = "DVN", `DXC Technology Co` = "DXC", `DexCom Inc` = "DXCM.O", 
`Electronic Arts Inc` = "EA.O", `eBay Inc` = "EBAY.O", `Ecolab Inc` = "ECL", 
`Consolidated Edison Inc` = "ED", `Equifax Inc` = "EFX", `Edison International` = "EIX", 
`Estee Lauder Companies Inc` = "EL", `Eastman Chemical Co` = "EMN", 
`Emerson Electric Co` = "EMR", `EOG Resources Inc` = "EOG", `Equinix Inc` = "EQIX.O", 
`Equity Residential` = "EQR", `Eversource Energy` = "ES", `Essex Property Trust Inc` = "ESS", 
`Eaton Corporation PLC` = "ETN", `Entergy Corp` = "ETR", `ETSY Inc` = "ETSY.O", 
`Evergy Inc` = "EVRG.K", `Edwards Lifesciences Corp` = "EW", 
`Exelon Corp` = "EXC.O", `Expeditors International of Washington Inc` = "EXPD.O", 
`Expedia Group Inc` = "EXPE.O", `Extra Space Storage Inc` = "EXR", 
`Ford Motor Co` = "F", `Diamondback Energy Inc` = "FANG.O", `Fastenal Co` = "FAST.O", 
`Facebook Inc` = "FB.O", `Fortune Brands Home & Security Inc` = "FBHS.K", 
`Freeport-McMoRan Inc` = "FCX", `FedEx Corp` = "FDX", `FirstEnergy Corp` = "FE", 
`F5 Networks Inc` = "FFIV.O", `Fidelity National Information Services Inc` = "FIS", 
`Fiserv Inc` = "FISV.O", `Fifth Third Bancorp` = "FITB.O", `FLIR Systems Inc` = "FLIR.O", 
`Flowserve Corp` = "FLS", `Fleetcor Technologies Inc` = "FLT", 
`FMC Corp` = "FMC", `Fox Corp` = "FOX.O", `Fox Corp` = "FOXA.O", 
`First Republic Bank` = "FRC", `Federal Realty Investment Trust` = "FRT", 
`TechnipFMC PLC` = "FTI", `Fortinet Inc` = "FTNT.O", `Fortive Corp` = "FTV", 
`General Dynamics Corp` = "GD", `General Electric Co` = "GE", 
`Gilead Sciences Inc` = "GILD.O", `General Mills Inc` = "GIS", 
`Globe Life Inc` = "GL", `Corning Inc` = "GLW", `General Motors Co` = "GM", 
`Alphabet Inc` = "GOOG.O", `Alphabet Inc` = "GOOGL.O", `Genuine Parts Co` = "GPC", 
`Global Payments Inc` = "GPN", `Gap Inc` = "GPS", `Garmin Ltd` = "GRMN.O", 
`Goldman Sachs Group Inc` = "GS", `W W Grainger Inc` = "GWW", 
`Halliburton Co` = "HAL", `Hasbro Inc` = "HAS.O", `Huntington Bancshares Inc` = "HBAN.O", 
`HanesBrands Inc` = "HBI", `HCA Healthcare Inc` = "HCA", `Home Depot Inc` = "HD", 
`Hess Corp` = "HES", `HollyFrontier Corp` = "HFC", `Hartford Financial Services Group Inc` = "HIG", 
`Huntington Ingalls Industries Inc` = "HII", `Hilton Worldwide Holdings Inc` = "HLT", 
`Hologic Inc` = "HOLX.O", `Honeywell International Inc` = "HON", 
`Hewlett Packard Enterprise Co` = "HPE", `HP Inc` = "HPQ", `Hormel Foods Corp` = "HRL", 
`Henry Schein Inc` = "HSIC.O", `Host Hotels & Resorts Inc` = "HST.O", 
`Hershey Co` = "HSY", `Humana Inc` = "HUM", `Howmet Aerospace Inc` = "HWM", 
`International Business Machines Corp` = "IBM", `Intercontinental Exchange Inc` = "ICE", 
`IDEXX Laboratories Inc` = "IDXX.O", `IDEX Corp` = "IEX", `International Flavors & Fragrances Inc` = "IFF", 
`Illumina Inc` = "ILMN.O", `Incyte Corp` = "INCY.O", `IHS Markit Ltd` = "INFO.K", 
`Intel Corp` = "INTC.O", `Intuit Inc` = "INTU.O", `International Paper Co` = "IP", 
`Interpublic Group of Companies Inc` = "IPG", `IPG Photonics Corp` = "IPGP.O", 
`IQVIA Holdings Inc` = "IQV", `Ingersoll Rand Inc` = "IR", `Iron Mountain Inc` = "IRM", 
`Intuitive Surgical Inc` = "ISRG.O", `Gartner Inc` = "IT", `Illinois Tool Works Inc` = "ITW", 
`Invesco Ltd` = "IVZ", `Jacobs Engineering Group Inc` = "J", 
`J B Hunt Transport Services Inc` = "JBHT.O", `Johnson Controls International PLC` = "JCI", 
`Jack Henry & Associates Inc` = "JKHY.O", `Johnson & Johnson` = "JNJ", 
`Juniper Networks Inc` = "JNPR.K", `JPMorgan Chase & Co` = "JPM", 
`Kellogg Co` = "K", KeyCorp = "KEY", `Keysight Technologies Inc` = "KEYS.K", 
`Kraft Heinz Co` = "KHC.O", `Kimco Realty Corp` = "KIM", `KLA Corp` = "KLAC.O", 
`Kimberly-Clark Corp` = "KMB", `Kinder Morgan Inc` = "KMI", `Carmax Inc` = "KMX", 
`Coca-Cola Co` = "KO", `Kroger Co` = "KR", `Kansas City Southern` = "KSU", 
`Loews Corp` = "L", `L Brands Inc` = "LB", `Leidos Holdings Inc` = "LDOS.K", 
`Leggett & Platt Inc` = "LEG", `Lennar Corp` = "LEN", `Laboratory Corporation of America Holdings` = "LH", 
`L3harris Technologies Inc` = "LHX", `Linde PLC` = "LIN", `LKQ Corp` = "LKQ.O", 
`Eli Lilly and Co` = "LLY", `Lockheed Martin Corp` = "LMT", `Lincoln National Corp` = "LNC", 
`Alliant Energy Corp` = "LNT.O", `Lowe's Companies Inc` = "LOW", 
`Lam Research Corp` = "LRCX.O", `Centurylink Inc` = "LUMN.K", 
`Southwest Airlines Co` = "LUV", `Las Vegas Sands Corp` = "LVS", 
`Lamb Weston Holdings Inc` = "LW", `LyondellBasell Industries NV` = "LYB", 
`Live Nation Entertainment Inc` = "LYV", `Mastercard Inc` = "MA", 
`Mid-America Apartment Communities Inc` = "MAA", `Marriott International Inc` = "MAR.O", 
`Masco Corp` = "MAS", `Mcdonald's Corp` = "MCD", `Microchip Technology Inc` = "MCHP.O", 
`Mckesson Corp` = "MCK", `Moody's Corp` = "MCO", `Mondelez International Inc` = "MDLZ.O", 
`Medtronic PLC` = "MDT", `MetLife Inc` = "MET", `MGM Resorts International` = "MGM", 
`Mohawk Industries Inc` = "MHK", `McCormick & Company Inc` = "MKC", 
`Marketaxess Holdings Inc` = "MKTX.O", `Martin Marietta Materials Inc` = "MLM", 
`Marsh & McLennan Companies Inc` = "MMC", `3M Co` = "MMM", `Monster Beverage Corp` = "MNST.O", 
`Altria Group Inc` = "MO", `Mosaic Co` = "MOS", `Marathon Petroleum Corp` = "MPC", 
`Merck & Co Inc` = "MRK", `Marathon Oil Corp` = "MRO", `Morgan Stanley` = "MS", 
`MSCI Inc` = "MSCI.K", `Microsoft Corp` = "MSFT.O", `Motorola Solutions Inc` = "MSI", 
`M&T Bank Corp` = "MTB", `Mettler-Toledo International Inc` = "MTD", 
`Micron Technology Inc` = "MU.O", `Maxim Integrated Products Inc` = "MXIM.O", 
`Norwegian Cruise Line Holdings Ltd` = "NCLH.K", `Nasdaq Inc` = "NDAQ.O", 
`Nextera Energy Inc` = "NEE", `Newmont Corporation` = "NEM", 
`Netflix Inc` = "NFLX.O", `NiSource Inc` = "NI", `Nike Inc` = "NKE", 
`NortonLifeLock Inc` = "NLOK.O", `Nielsen Holdings PLC` = "NLSN.K", 
`Northrop Grumman Corp` = "NOC", `National Oilwell Varco Inc` = "NOV", 
`ServiceNow Inc` = "NOW", `NRG Energy Inc` = "NRG", `Norfolk Southern Corp` = "NSC", 
`NetApp Inc` = "NTAP.O", `Northern Trust Corp` = "NTRS.O", `Nucor Corp` = "NUE", 
`NVIDIA Corp` = "NVDA.O", `NVR Inc` = "NVR", `Newell Brands Inc` = "NWL.O", 
`News Corp` = "NWS.O", `News Corp` = "NWSA.O", `Realty Income Corp` = "O", 
`Old Dominion Freight Line Inc` = "ODFL.O", `ONEOK Inc` = "OKE", 
`Omnicom Group Inc` = "OMC", `Oracle Corp` = "ORCL.K", `O'Reilly Automotive Inc` = "ORLY.O", 
`Otis Worldwide Corp` = "OTIS.K", `Occidental Petroleum Corp` = "OXY", 
`Paycom Software Inc` = "PAYC.K", `Paychex Inc` = "PAYX.O", `People's United Financial Inc` = "PBCT.O", 
`Paccar Inc` = "PCAR.O", `Healthpeak Properties Inc` = "PEAK.K", 
`Public Service Enterprise Group Inc` = "PEG", `PepsiCo Inc` = "PEP.O", 
`Pfizer Inc` = "PFE", `Principal Financial Group Inc` = "PFG.O", 
`Procter & Gamble Co` = "PG", `Progressive Corp` = "PGR", `Parker-Hannifin Corp` = "PH", 
`Pultegroup Inc` = "PHM", `Packaging Corp of America` = "PKG", 
`PerkinElmer Inc` = "PKI", `Prologis Inc` = "PLD", `Philip Morris International Inc` = "PM", 
`PNC Financial Services Group Inc` = "PNC", `Pentair PLC` = "PNR", 
`Pinnacle West Capital Corp` = "PNW", `Pool Corp` = "POOL.O", 
`PPG Industries Inc` = "PPG", `PPL Corp` = "PPL", `Perrigo Company PLC` = "PRGO.K", 
`Prudential Financial Inc` = "PRU", `Public Storage` = "PSA", 
`Phillips 66` = "PSX", `PVH Corp` = "PVH", `Quanta Services Inc` = "PWR", 
`Pioneer Natural Resources Co` = "PXD", `PayPal Holdings Inc` = "PYPL.O", 
`Qualcomm Inc` = "QCOM.O", `Qorvo Inc` = "QRVO.O", `Royal Caribbean Cruises Ltd` = "RCL", 
`Everest Re Group Ltd` = "RE", `Regency Centers Corp` = "REG.O", 
`Regeneron Pharmaceuticals Inc` = "REGN.O", `Regions Financial Corp` = "RF", 
`Robert Half International Inc` = "RHI", `Raymond James Financial Inc` = "RJF", 
`Ralph Lauren Corp` = "RL", `Resmed Inc` = "RMD", `Rockwell Automation Inc` = "ROK", 
`Rollins Inc` = "ROL", `Roper Technologies Inc` = "ROP", `Ross Stores Inc` = "ROST.O", 
`Republic Services Inc` = "RSG", `Raytheon Technologies Corp` = "RTX", 
`SBA Communications Corp` = "SBAC.O", `Starbucks Corp` = "SBUX.O", 
`Charles Schwab Corp` = "SCHW.K", `Sealed Air Corp` = "SEE", 
`Sherwin-Williams Co` = "SHW", `SVB Financial Group` = "SIVB.O", 
`J M Smucker Co` = "SJM", `Schlumberger NV` = "SLB", `SL Green Realty Corp` = "SLG", 
`Snap-On Inc` = "SNA", `Synopsys Inc` = "SNPS.O", `Southern Co` = "SO", 
`Simon Property Group Inc` = "SPG", `S&P Global Inc` = "SPGI.K", 
`Sempra Energy` = "SRE", `Steris plc` = "STE", `State Street Corp` = "STT", 
`Seagate Technology PLC` = "STX.O", `Constellation Brands Inc` = "STZ", 
`Stanley Black & Decker Inc` = "SWK", `Skyworks Solutions Inc` = "SWKS.O", 
`Synchrony Financial` = "SYF", `Stryker Corp` = "SYK", `Sysco Corp` = "SYY", 
`AT&T Inc` = "T", `Molson Coors Beverage Co` = "TAP", `TransDigm Group Inc` = "TDG", 
`Teledyne Technologies Inc` = "TDY", `TE Connectivity Ltd` = "TEL", 
`Teradyne Inc` = "TER.O", `Truist Financial Corp` = "TFC", `Teleflex Inc` = "TFX", 
`Target Corp` = "TGT", `Tiffany & Co` = "TIF", `TJX Companies Inc` = "TJX", 
`Thermo Fisher Scientific Inc` = "TMO", `T-Mobile US Inc` = "TMUS.O", 
`Tapestry Inc` = "TPR", `T. Rowe Price Group Inc` = "TROW.O", 
`Travelers Companies Inc` = "TRV", `Tractor Supply Co` = "TSCO.O", 
`Tyson Foods Inc` = "TSN", `Trane Technologies PLC` = "TT", `Take-Two Interactive Software Inc` = "TTWO.O", 
`Twitter Inc` = "TWTR.K", `Texas Instruments Inc` = "TXN.O", 
`Textron Inc` = "TXT", `Tyler Technologies Inc` = "TYL", `Under Armour Inc` = "UA", 
`Under Armour Inc` = "UAA", `United Airlines Holdings Inc` = "UAL.O", 
`UDR Inc` = "UDR", `Universal Health Services Inc` = "UHS", `Ulta Beauty Inc` = "ULTA.O", 
`UnitedHealth Group Inc` = "UNH", `Unum Group` = "UNM", `Union Pacific Corp` = "UNP", 
`United Parcel Service Inc` = "UPS", `United Rentals Inc` = "URI", 
`U.S. Bancorp` = "USB", `Visa Inc` = "V", `Varian Medical Systems Inc` = "VAR", 
`VF Corp` = "VFC", `ViacomCBS Inc` = "VIAC.O", `Valero Energy Corp` = "VLO", 
`Vulcan Materials Co` = "VMC", `Vornado Realty Trust` = "VNO", 
`Vontier Corp` = "VNT", `Verisk Analytics Inc` = "VRSK.O", `Verisign Inc` = "VRSN.O", 
`Vertex Pharmaceuticals Inc` = "VRTX.O", `Ventas Inc` = "VTR", 
`Mylan NV` = "VTRS.O", `Verizon Communications Inc` = "VZ", `Westinghouse Air Brake Technologies Corp` = "WAB", 
`Waters Corp` = "WAT", `Walgreens Boots Alliance Inc` = "WBA.O", 
`Western Digital Corp` = "WDC.O", `WEC Energy Group Inc` = "WEC", 
`Welltower Inc` = "WELL.K", `Wells Fargo & Co` = "WFC", `Whirlpool Corp` = "WHR", 
`Willis Towers Watson PLC` = "WLTW.O", `Waste Management Inc` = "WM", 
`Williams Companies Inc` = "WMB", `Walmart Inc` = "WMT", `W. R. Berkley Corp` = "WRB", 
`Westrock Co` = "WRK", `West Pharmaceutical Services Inc` = "WST", 
`Western Union Co` = "WU", `Weyerhaeuser Co` = "WY", `Wynn Resorts Ltd` = "WYNN.O", 
`Xcel Energy Inc` = "XEL.O", `Xilinx Inc` = "XLNX.O", `Exxon Mobil Corp` = "XOM", 
`DENTSPLY SIRONA Inc` = "XRAY.O", `Xerox Holdings Corp` = "XRX", 
`Xylem Inc` = "XYL", `Yum! Brands Inc` = "YUM", `Zimmer Biomet Holdings Inc` = "ZBH", 
`Zebra Technologies Corp` = "ZBRA.O", `Zions Bancorporation NA` = "ZION.O", 
`Zoetis Inc` = "ZTS")
