S <-
c("JPM", "V", "DIS", "BA", "XOM", "BRKb", "MRK", "HD", "MA", 
"BAC", "UNH", "KO", "WMT", "GNRC.K", "JNJ", "PG", "WFC", "VZ", 
"CVX", "HON", "LMT", "NKE", "ORCL.K", "T", "MCD", "UPS", "PFE", 
"C", "TWTR.K", "TMO", "NEM", "BMY", "FDX", "LOW", "ACN", "CAT", 
"LLY", "CRM", "NEE", "DE", "DHR", "UNP", "GS", "MO", "TGT", "ETN", 
"GM", "ABT", "IBM", "USB", "COP", "HPQ", "MMM", "ABBV.K", "FCX", 
"F", "TJX", "MDT", "RTX", "CCL", "ITW", "AMT", "PM", "EL", "BLK", 
"MS", "PNC", "CI", "ANTM.K", "ALL", "LIN", "GE", "DG", "MPC", 
"DUK", "HUM", "NOW", "SPGI.K", "PXD", "BBY", "CCI", "MET", "AXP", 
"SPG", "TFC", "KMB", "VLO", "CVS", "AON", "CL", "VFC", "ED", 
"CMI", "AZO", "SCHW.K", "EMR", "HIG", "AMP", "RF", "DFS", "SRE", 
"PLD", "ZTS", "PRU", "TEL", "SHW", "IFF", "CB", "OXY", "NSC", 
"BDX", "RCL", "SYK", "MMC", "COF", "EOG", "BK", "O", "KEY", "LHX", 
"GD", "LEN", "STT", "DAL", "MCO", "CTLT.K", "FIS", "D", "GPN", 
"WM", "AFL", "INFO.K", "PGR", "TT", "IP", "LYB", "APTV.K", "SLB", 
"ROP", "DHI", "APD", "CFG", "PSX", "HCA", "DLR", "NOC", "LUV", 
"DD", "TRV", "CLX", "SYF", "GLW", "BSX", "DOW", "MCK", "KR", 
"GIS", "ECL", "ADM", "OMC", "HLT", "SWK", "BLL", "DVN", "SO", 
"JCI", "MTB", "CTVA.K", "PSA", "AWK", "ICE", "CMG", "NRG", "MRO", 
"AIG", "BKR", "TSN", "PPG", "PPL", "TSLA.O", "CMA", "KSU", "AAPL.O", 
"ETR", "YUM", "EMN", "PH", "AMZN.O", "MTD", "BAX", "WEC", "MSFT.O", 
"FRC", "EW", "HAL", "WHR", "FB.O", "AJG", "NCLH.K", "APH", "KMI", 
"MGM", "AAP", "NXPI.O", "DPZ", "GOOG.O", "OKE", "K", "CMS", "URI", 
"SYY", "ES", "GOOGL.O", "EQR", "VIAC.O", "NUE", "AVB", "NVDA.O", 
"AVGO.O", "GPC", "HES", "GWW", "MSCI.K", "EIX", "IPG", "CARR.K", 
"LVS", "SJM", "WU", "EXR", "ANET.K", "IVZ", "DRI", "CNC", "NVR", 
"A", "ROK", "WMB", "ZBH", "PKI", "DTE", "SNA", "WRK", "FE", "CHD", 
"STZ", "ESS", "ARE", "OTIS.K", "IQV", "INTC.O", "IR", "ALB", 
"PHM", "RSG", "RHI", "FLT", "WELL.K", "KMX", "AEE", "STE", "LUMN.K", 
"HSY", "CE", "ABC", "HPE", "PEG", "WY", "AES", "TDG", "WST", 
"KEYS.K", "VTR", "LYV", "DOV", "COO", "LB", "MKC", "AVY", "PKG", 
"BEN", "NI", "MAS", "VAR", "AMD.O", "XYL", "EVRG.K", "BWA", "RL", 
"TYL", "MSI", "MHK", "FTV", "MAA", "NFLX.O", "RMD", "EFX", "CAG", 
"AMCR.K", "LH", "TPR", "ALLE.K", "CAH", "DGX", "VMC", "AME", 
"CBRE.K", "PEAK.K", "ROL", "ALK", "MOS", "TAP", "PYPL.O", "JNPR.K", 
"VNO", "BXP", "IT", "CNP", "RJF", "MLM", "NLSN.K", "GPS", "WAT", 
"L", "BR", "LNC", "UNM", "PENN.O", "QCOM.O", "ATO", "AIZ", "PAYC.K", 
"WAB", "CF", "MU.O", "LDOS.K", "DRE", "CPB", "HWM", "PNW", "UDR", 
"KIM", "AMGN.O", "IEX", "COG", "CSCO.O", "FMC", "HRL", "BFb", 
"TDY", "FRT", "PWR", "HII", "ADBE.O", "HFC", "PEP.O", "TFX", 
"HBI", "CZR.O", "LEG", "DVA", "FBHS.K", "UAA", "TXT", "CMCSA.O", 
"SBUX.O", "CHTR.O", "UHS", "AOS", "COST.O", "BIO", "NOV", "PVH", 
"IRM", "TXN.O", "AMAT.O", "WRB", "RE", "J", "LRCX.O", "BKNG.O", 
"PRGO.K", "PNR", "INTU.O", "LW", "DISCA.O", "GL", "KLAC.O", "DISCK.O", 
"ADP.O", "DXC", "UAL.O", "UA", "SEE", "AAL.O", "ETSY.O", "MDLZ.O", 
"ATVI.O", "TMUS.O", "GILD.O", "ADI.O", "ENPH.O", "EXPE.O", "CME.O", 
"MAR.O", "ALGN.O", "XLNX.O", "FITB.O", "AEP.O", "CSX.O", "ROST.O", 
"MCHP.O", "BIIB.O", "ILMN.O", "FANG.O", "FISV.O", "EBAY.O", "WBA.O", 
"SIVB.O", "REGN.O", "EA.O", "ISRG.O", "SWKS.O", "STX.O", "EQIX.O", 
"ALXN.O", "TER.O", "ORLY.O", "ADSK.O", "XEL.O", "ULTA.O", "VRTX.O", 
"PAYX.O", "FAST.O", "FTNT.O", "TROW.O", "DXCM.O", "ZBRA.O", "VRSK.O", 
"CTSH.O", "EXC.O", "MXIM.O", "IDXX.O", "WYNN.O", "CDNS.O", "MPWR.O", 
"SNPS.O", "SBAC.O", "CERN.O", "KHC.O", "WDC.O", "CINF.O", "NDAQ.O", 
"HBAN.O", "NTRS.O", "TTWO.O", "TSCO.O", "POOL.O", "CTAS.O", "QRVO.O", 
"WLTW.O", "DLTR.O", "PCAR.O", "MNST.O", "FOXA.O", "LNT.O", "PFG.O", 
"VRSN.O", "CTXS.O", "ANSS.O", "MKTX.O", "FFIV.O", "AKAM.O", "ODFL.O", 
"ZION.O", "NTAP.O", "CDW.O", "CPRT.O", "EXPD.O", "HOLX.O", "HAS.O", 
"HST.O", "NWSA.O", "APA.O", "CHRW.O", "VTRS.O", "INCY.O", "DISH.O", 
"TRMB.O", "PBCT.O", "GRMN.O", "ABMD.O", "LKQ.O", "REG.O", "JBHT.O", 
"FLIR.O", "NWL.O", "JKHY.O", "NLOK.O", "HSIC.O", "XRAY.O", "CBOE.K", 
"FOX.O", "IPGP.O", "NWS.O")
